// schema auto-generated by http://json2ts.com/
export interface Vehicle {
  id: number;
  uvid: number;
  uuid: string;
  squishVin: string;
  year: number;
  make: string;
  model: string;
  trim: string;
  body: string;
  type: string;
  class: string;
  engine: string;
  fuel: string;
  transmission: string;
  driveline: string;
  revisionCount: number;
  updated: string;
  repository: string;
}
